spring:
  application:
    name: sizeguide-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/sizeguide
      auto-index-creation: true
  datasource:
    oracle:
      url: jdbc:oracle:thin:@pp2db.cx0j3oma32zw.ap-south-1.rds.amazonaws.com:1621/PP2DB
      username: MPLUATCOM
      password: Us976TM64BKK
      driver-class-name: oracle.jdbc.driver.OracleDriver
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  quartz:
    job-store-type: memory
    properties:
      org.quartz.threadPool.threadCount: 5

aws:
  access:
    key: ${AWS_ACCESS_KEY:test}
  secret:
    key: ${AWS_SECRET_KEY:test}
  region: ${AWS_REGION:us-east-1}
  s3:
    bucket: ${S3_BUCKET_NAME:sizeguide-templates}

opentelemetry:
  traces:
    exporter: otlp
    endpoint: ${OTLP_ENDPOINT:http://localhost:4317}

server:
  port: 8080
  servlet:
    context-path: /api/v1

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    
logging:
  level:
    com.sizeguide: INFO
    com.sizeguide.datamigration: DEBUG
    org.springframework.batch: DEBUG
    org.springframework.jdbc: DEBUG
    org.springframework.data.mongodb: DEBUG
    org.springframework.transaction: DEBUG

app:
  validation:
    batch-size: 1000
    max-file-size: 10MB
  email:
    from: noreply@sizeguide.com
    subject-prefix: "[SizeGuide] "

batch:
  chunk-size: 100

migration:
  auto-run: false  # Set to true to run migration automatically on startup
