spring:
  application:
    name: sizeguide-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/sizeguide
      auto-index-creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  quartz:
    job-store-type: memory
    properties:
      org.quartz.threadPool.threadCount: 5

aws:
  access:
    key: ${AWS_ACCESS_KEY:test}
  secret:
    key: ${AWS_SECRET_KEY:test}
  region: ${AWS_REGION:us-east-1}
  s3:
    bucket: ${S3_BUCKET_NAME:sizeguide-templates}

opentelemetry:
  traces:
    exporter: otlp
    endpoint: ${OTLP_ENDPOINT:http://localhost:4317}

server:
  port: 8080
  servlet:
    context-path: /api/v1

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    
logging:
  level:
    com.sizeguide: INFO
    org.springframework.data.mongodb: INFO

app:
  validation:
    batch-size: 1000
    max-file-size: 10MB
  email:
    from: noreply@sizeguide.com
    subject-prefix: "[SizeGuide] "
